feat: test partitions before directory on preserve
It doesn't matter if p2 is fat32 and directory overlay has been selected on preserve if  p1 would fail the test to use preserve, so move the later test of p1 and p2 before the former so it fails before, if it has to.

Change order of test conditions on fat32 and directory overlay on normal mode to mirror the analogue test on preserve. A cosmetic change for consistency.

Signed-off-by: Manuel Fombuena <fombuena@outlook.com>

diff --git a/yastfli b/yastfli
--- a/yastfli
+++ b/yastfli
@@ -156,17 +156,17 @@ elif ! [[ -b "${tgt}" ]]; then
 elif [[ "${datafs}" != "ext4" && "${datafs}" != "fat32" ]]; then
   echo "ERROR: invalid data partition filesystem "${datafs}". It can only be ext4 or fat32"
   exit 1
-elif [[ ${dirovl} == true && "${datafs}" == "fat32" && \
-        ${noovl} == false && ${nofmt} == false ]]; then
+elif [[ ${nofmt} == false && ${dirovl} == true && \
+        "${datafs}" == "fat32" && ${noovl} == false ]]; then
   echo "ERROR: fat32 is not compatible with directory overlay. Use file or change to ext4"
-  exit 1
-elif [[ ${dirovl} == true && "${tgtp2fs}" == "fat32" && \
-        ${noovl} == false && ${nofmt} == true ]]; then
-  echo "ERROR: filesystem on "${tgtp2}" is fat32 and not compatible with directory overlay"
   exit 1
 elif [[ ${nofmt} == true && \
   (( "${tgtp1fs}" != "fat32" ) || ("${tgtp2fs}" != "ext4" && "${tgtp2fs}" != "fat32" )) ]]; then 
   echo "ERROR: preserve mode can't be used with this device. Was yastfli used to create the Live OS?"
+  exit 1
+elif [[ ${nofmt} == true  && ${dirovl} == true && \
+        "${tgtp2fs}" == "fat32" && ${noovl} == false ]]; then
+  echo "ERROR: filesystem on "${tgtp2}" is fat32 and not compatible with directory overlay"
   exit 1
 fi
 if [[ ${nofmt} == true ]]; then
